#!/bin/bash

# Set the PID of the server
SERVER_PID=$1
# Number of times to run the command
TIMES=1

# Base message
BASE_MESSAGE="$c3b!c3a$!!ba$c2b1!bb12a$1cb!!%!%1ca3!%a2%bacba$32%aabc$2$%!c233223%!b%a%2ba%a%3$!3ba31!b113%b!aa!ca"

VIOLATOR_MESSAGE="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed imperdiet augue id facilisis rutrum. Proin tristique fermentum magna, et faucibus quam volutpat finibus. Aliquam pretium elit quis lorem faucibus, rutrum mollis est imperdiet. Aliquam lectus nisl, ultricies sit amet elementum et, accumsan dignissim ex. Vivamus volutpat sollicitudin accumsan. Phasellus vitae egestas nunc. Donec tincidunt ultricies lacus vitae aliquam. Cras metus eros, varius a tellus et, molestie efficitur quam. In id convallis turpis, nec condimentum orci. Proin lacinia bibendum congue.

Ut tristique dignissim dictum. Duis sodales dui pretium commodo mollis. Proin tempor fermentum tincidunt. Nam non tellus a metus lobortis tincidunt. Maecenas accumsan vehicula mi, vitae imperdiet leo faucibus sit amet. Aliquam blandit eu diam sed malesuada. Nullam id sagittis sapien, sed porttitor mauris. Praesent lectus est, vehicula nec quam sed, porttitor maximus ipsum. Aliquam tempus, nibh nec finibus maximus, tortor augue consectetur metus, pellentesque fringilla turpis ligula non libero. Mauris quis porttitor quam. Vivamus eleifend egestas pharetra. Nunc suscipit cursus nunc in egestas. Vestibulum commodo nisi lorem, ut rhoncus erat sodales feugiat. Donec sed ipsum pharetra, lobortis quam et, aliquet ipsum. Aliquam erat volutpat.

Maecenas ultrices ante vel ornare facilisis. Nam pellentesque arcu ac ipsum pulvinar tempor. Duis quis elit a mauris vulputate interdum sed non libero. Aenean quis libero pellentesque arcu sagittis maximus sit amet ut augue. Fusce in sem elementum eros pharetra sodales. Cras pretium leo non leo sagittis lobortis. Ut varius, orci at sollicitudin euismod, turpis ipsum porta nulla, at volutpat diam neque eu nibh. Nam nisl velit, facilisis nec sapien ut, feugiat interdum libero. Maecenas semper auctor nunc accumsan tempus. Cras tempus porta nunc eget scelerisque. Pellentesque lacus nisl, ornare non aliquam sit amet, ultrices non velit.

Suspendisse at mollis lorem. Proin eu quam vitae tellus tristique tristique a vitae nunc. Donec mollis laoreet augue, sit amet sodales erat porta quis. Donec venenatis non ex in tristique. Phasellus interdum justo rhoncus est euismod vestibulum. Vivamus porttitor sit amet augue nec iaculis. Cras sit amet pulvinar justo, sed mattis urna. Cras lacinia lacus eget finibus ullamcorper. Vestibulum ullamcorper, ligula ac blandit congue, risus urna viverra augue, sit amet facilisis enim dui quis eros. Pellentesque ultrices vitae diam et tempor. Maecenas ut nunc nec arcu interdum blandit sed nec ante. Donec orci erat, interdum ac vehicula eu, egestas et felis. Nullam dapibus mattis lorem. Aenean sed velit dapibus, dapibus lacus vitae, rutrum ligula. Duis accumsan dictum purus, nec consequat augue porttitor in.

Phasellus nunc tellus, tempor sit amet purus non, sodales auctor ligula. Curabitur facilisis tellus lorem, non porttitor lorem faucibus nec. Donec sed turpis interdum, vehicula sapien non, tincidunt ex. Ut augue enim, imperdiet in nulla sit amet, vehicula lobortis mauris. Vestibulum bibendum est non massa rhoncus, in mattis felis auctor. Integer id efficitur libero. Nam dictum lorem quis orci egestas vestibulum. Integer vulputate at augue vitae mollis. Suspendisse tortor urna, pharetra at nibh mattis, iaculis feugiat diam. Pellentesque vel tellus erat. Nam congue velit velit, ut dignissim neque congue et. Cras convallis luctus elit, elementum auctor ex egestas nec. Quisque eget dignissim ligula. Sed vitae fermentum massa, at interdum mi. Etiam sollicitudin enim at nibh aliquam, ut maximus dolor bibendum. Cras hendrerit dolor non nisl vulputate ornare.

Vivamus finibus vitae lectus id laoreet. Nunc at neque nec enim finibus elementum quis quis massa. Fusce pharetra sit amet felis sit amet efficitur. Fusce ac augue nec erat volutpat dictum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam venenatis interdum ante at finibus. Maecenas sodales massa justo, in dignissim lorem laoreet ac. Pellentesque ullamcorper laoreet aliquet. Vestibulum gravida nisi nisi, ut mattis ligula feugiat non. Nunc felis sem, molestie in sodales et, tincidunt a ipsum. In suscipit lacus ac ex pellentesque pretium. Etiam non nibh lorem.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non vehicula turpis. Aliquam erat volutpat. Praesent finibus lorem est, sed condimentum ante venenatis vel. Integer a commodo dolor, eget consectetur erat. Pellentesque in eleifend tortor. Vestibulum vel tristique ipsum. Etiam in molestie erat. Quisque ut tempus justo. Nunc dui est, varius non malesuada non, condimentum sed ipsum. Vestibulum cursus efficitur enim a vehicula. Fusce molestie, nibh ut tristique faucibus, purus eros tempor elit, et imperdiet purus purus eu nibh. Mauris dictum quam et euismod sollicitudin.

Nunc nec diam nec sem sodales vehicula at ac enim. Duis mollis faucibus congue. Suspendisse dictum fringilla sollicitudin. Nulla interdum laoreet commodo. Duis sed elementum dolor, id rutrum elit. Nullam sagittis diam ipsum. Maecenas ante magna, faucibus eget faucibus ac, dignissim in magna. Vestibulum nec ante lorem. Praesent gravida massa neque, non maximus magna maximus auctor. Ut eget dapibus magna. Morbi in eleifend leo, in porttitor arcu. Donec egestas felis mi, non pulvinar velit dignissim a. Nulla posuere, justo nec ultrices scelerisque, velit ex ultricies nulla, et elementum felis arcu sit amet nulla.

Etiam mauris dolor, blandit eu bibendum nec, sodales in sapien. Phasellus sed nulla viverra, sagittis urna quis, ultrices arcu. Sed quis orci sed nisl mollis ornare. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus faucibus neque fringilla, lobortis sem quis, varius justo. Nam in venenatis libero. Suspendisse interdum id urna sit amet ullamcorper. Etiam egestas quam sollicitudin, tempor tellus sagittis, vulputate nulla. Phasellus laoreet varius tempus. Duis ac pulvinar enim. Cras laoreet justo ut dolor ornare, quis bibendum diam tristique. Quisque ante magna, molestie eu luctus vel, condimentum at purus. Cras iaculis tincidunt ante, ut finibus diam placerat id. Etiam eu sapien vel elit tristique posuere. Ut massa magna, venenatis eget dolor convallis, malesuada ultricies tellus. Nunc vel diam at lectus maximus lobortis dignissim vulputate orci.

Maecenas eros velit, blandit vitae ligula a, bibendum venenatis augue. Nam nulla justo, facilisis vel congue a, fermentum non mi. Pellentesque vulputate interdum aliquam. Suspendisse laoreet neque vel sem imperdiet condimentum. Praesent tempor nec tellus non commodo. Praesent ultrices euismod mollis. Sed pretium blandit nunc, sit amet varius quam gravida at. Nunc mi odio, iaculis ut commodo at, porta eu tellus. Aliquam ornare eros non dictum laoreet. Suspendisse id tortor eu purus ultricies iaculis. Sed venenatis sem eget nunc bibendum facilisis. Proin non nisi vel lacus elementum molestie. Curabitur rhoncus suscipit dui rutrum egestas. Phasellus tempor suscipit interdum. Donec pellentesque ipsum vel neque consequat rhoncus. Pellentesque sed nisi at nulla fringilla tempus.

Donec in accumsan ex, nec pulvinar odio. Quisque convallis dui non mattis pharetra. Phasellus in dapibus tellus. Sed sit amet neque sed sem luctus aliquet. Curabitur venenatis, quam et imperdiet convallis, felis sapien pharetra felis, vel tempor diam velit quis tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac ultricies libero, vitae efficitur diam.

Nulla ex tortor, egestas vitae efficitur fringilla, venenatis at purus. Maecenas scelerisque ullamcorper sem, at faucibus felis fermentum eget. Aliquam tempor magna mauris, in dictum eros interdum tempor. Quisque ornare id dolor quis vulputate. Fusce fermentum fringilla ipsum, eget placerat ligula pulvinar vel. In posuere purus leo, sit amet efficitur risus suscipit sit amet. Nullam et purus elementum, volutpat mi at, sollicitudin magna. Mauris et erat vehicula, commodo enim sed, mollis massa. Vivamus aliquet rutrum tincidunt. Aliquam sit amet dignissim purus. Etiam vehicula dapibus luctus. Aliquam pretium ex non imperdiet gravida.

Aliquam vestibulum quam libero. Vivamus vitae sollicitudin neque. Ut cursus urna in facilisis efficitur. Sed auctor faucibus vulputate. Aliquam diam dui, viverra vitae ex ac, posuere bibendum quam. Etiam non consectetur est. Nunc hendrerit laoreet arcu in pellentesque. Mauris pulvinar, dui non vehicula mattis, velit quam egestas eros, vel commodo dolor est vel urna. Etiam vitae ligula tempor, fringilla massa eu, pellentesque ipsum. Nullam convallis tellus at tortor viverra venenatis. Vivamus lobortis diam sit amet dui aliquet sodales.

Duis nec orci non purus efficitur elementum in ac orci. Maecenas at nisi in orci aliquam eleifend quis eu nunc. Maecenas libero nibh, ultrices vulputate metus ut, dignissim pretium lorem. Quisque dapibus vulputate enim vehicula iaculis. Curabitur nec venenatis mauris, in semper nibh. Proin venenatis sagittis quam, eget consequat mi aliquet sit amet. Praesent ut risus tortor. Maecenas a lorem varius, venenatis leo eget, maximus eros. Proin nec mauris hendrerit, vulputate purus id, faucibus urna. Duis a suscipit orci. In auctor luctus volutpat.

Proin elementum dignissim sagittis. Pellentesque ac turpis velit. In tincidunt dui ac erat varius suscipit. Cras porttitor, felis nec laoreet lobortis, risus purus dapibus libero, sed auctor ligula orci vel velit. Nunc at orci eget ante cursus posuere. Nunc urna mi, maximus et blandit vel, consequat ac nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam feugiat dapibus diam at posuere. Nunc sed velit fringilla, lobortis libero eget, laoreet arcu.

Duis auctor mi eget blandit placerat. Aenean auctor ipsum id justo laoreet viverra. Maecenas consectetur luctus libero tincidunt tristique. Donec egestas iaculis ipsum, vel accumsan tortor pulvinar ut. Vivamus et mollis nunc. Nulla maximus felis felis, eget eleifend lorem pretium nec. Duis ut nisl posuere, mattis enim a, consequat turpis. Praesent euismod eu mi nec semper. Curabitur fermentum augue in purus accumsan, non egestas massa placerat. Etiam quis dignissim nulla, in iaculis nisl. Maecenas elementum suscipit risus non pellentesque. Vestibulum egestas id quam ut imperdiet. Sed quis blandit ipsum, in tempor risus. Phasellus ac elementum est, ac gravida orci. Pellentesque blandit nunc eget fermentum suscipit.

Phasellus consectetur, ligula accumsan convallis congue, dolor odio aliquet velit, eget sodales ipsum lorem rhoncus justo. Etiam pharetra condimentum nulla in commodo. Aenean quis metus ut arcu fermentum consectetur. Curabitur semper viverra lacinia. Mauris fringilla non lorem vitae iaculis. Cras bibendum odio a felis molestie dictum. Nullam justo sem, tincidunt eu aliquet id, lacinia nec mauris. Proin pellentesque purus velit, non ornare elit malesuada et. Maecenas sollicitudin lorem ipsum, quis porta augue blandit vel. Nullam tempus fermentum velit eget tincidunt.

Nunc vestibulum vestibulum nisi nec vehicula. Suspendisse ac rhoncus ipsum. Mauris odio nulla, maximus ut tincidunt et, finibus ac erat. Etiam ipsum leo, ultricies vitae tempus et, pretium vitae felis. Sed sit amet nunc a enim aliquam dapibus. Nam lacus eros, volutpat et velit nec, feugiat semper magna. Morbi elementum accumsan nisi. Phasellus iaculis leo sit amet lacus pharetra, id dignissim augue fringilla. Integer vel pretium velit, sed sollicitudin neque. Maecenas ac pulvinar lorem. Mauris consequat gravida volutpat. Nam augue lacus, commodo nec pulvinar nec, pulvinar a arcu. Cras facilisis, urna eget suscipit ultricies, lorem mauris efficitur diam, eget faucibus arcu diam ac lectus. Quisque elementum ac nulla sed dignissim.

Nulla hendrerit pellentesque massa quis tincidunt. Mauris porta quam eu dolor tincidunt, eget tempor elit semper. Aliquam iaculis cursus diam, nec congue enim efficitur in. Vestibulum non arcu sed arcu faucibus lobortis. Suspendisse iaculis suscipit elit, a pulvinar nisl aliquam convallis. Pellentesque vehicula justo faucibus dolor sollicitudin placerat. Aenean libero nunc, efficitur condimentum auctor iaculis, aliquet et purus. Proin dapibus neque eros, ut gravida massa mattis et. Ut eu tempor diam, ut pellentesque velit. Curabitur interdum consequat ante, at varius ante fermentum nec.

Phasellus bibendum pharetra erat ac vestibulum. Suspendisse finibus tristique feugiat. Fusce eu tristique diam. Duis et convallis nibh. Aenean eu rutrum leo, sit amet dapibus nibh. Mauris mollis a enim ac lobortis. Nunc molestie sem ac cursus fermentum. Donec at nisi nec arcu euismod pulvinar id at dolor.

Suspendisse dapibus urna dui, et eleifend arcu vestibulum vel. Nulla aliquet aliquam dolor. Nulla mollis augue non leo aliquam varius sed id mauris. Nam euismod laoreet nisi, et pharetra metus cursus ac. Donec suscipit libero a risus congue, fringilla feugiat lorem posuere. Vivamus aliquet, massa non molestie lacinia, lectus lectus fringilla elit, non hendrerit justo nunc eu risus. Suspendisse potenti. Nulla facilisi. Phasellus ultricies laoreet tortor, ut fringilla nibh volutpat ut. Nam sit amet justo elementum enim mattis sagittis in vitae ipsum. Curabitur ullamcorper lorem neque, placerat interdum eros auctor quis. Sed venenatis lectus sit amet ultricies lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean ac leo tristique risus malesuada tristique.

Praesent rutrum, nisl ultricies mattis porta, lorem neque pharetra orci, consectetur blandit purus lorem nec sapien. Morbi porttitor nibh at varius semper. Pellentesque consectetur massa in pretium eleifend. Vestibulum eleifend lobortis diam vitae sagittis. Integer feugiat est et eros facilisis, a faucibus orci aliquam. Fusce tincidunt enim quis diam pulvinar, nec congue risus mollis. Phasellus eget ex cursus, eleifend erat sit amet, sodales erat. Nulla sed dui tempor, vestibulum dui mattis, molestie orci. Nulla vulputate nibh a tortor rhoncus ultricies. Phasellus sed augue id nunc venenatis interdum.

Fusce ut faucibus justo. Vivamus ac neque blandit, dictum ex vitae, imperdiet justo. Aliquam tristique magna erat, sed ornare magna volutpat sit amet. Cras dignissim auctor enim vitae congue. Mauris quam sem, laoreet id nisi a, dapibus venenatis ligula. Nam maximus sagittis suscipit. Suspendisse aliquet congue lectus, eget tempor orci convallis eu. Vestibulum porta erat nec leo consequat, et porta diam consequat. In aliquet tellus lacus, in aliquet quam euismod sed. Ut pellentesque laoreet volutpat. Donec nec vehicula dui, at gravida nisi. Donec dapibus nisl urna, sed vehicula purus imperdiet ut. Quisque id interdum augue. Nam iaculis, tortor vitae vehicula egestas, arcu odio feugiat sem, sed consectetur ex elit et quam. Aliquam eu arcu suscipit, pretium dolor vitae, varius ligula. Suspendisse at tellus id nunc tincidunt placerat.

Etiam pretium vel ante in semper. Ut pretium massa quis ultrices tempor. Fusce ex purus, tristique a hendrerit vel, consectetur eget libero. Donec tellus eros, consectetur a est nec, auctor mollis nisi. Phasellus porta condimentum laoreet. Praesent sagittis tristique mauris eget ultrices. Etiam porttitor, ante non vestibulum semper, lectus mauris ultricies lacus, ac lacinia lacus lacus sit amet velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce interdum ligula vitae tempor egestas. Aliquam nec massa mi. Vestibulum ultrices nulla ipsum, efficitur pulvinar orci feugiat sit amet. Mauris auctor est dictum nunc tempus pellentesque elementum sed est. Suspendisse aliquam orci mi, id aliquam sapien sodales et.

Curabitur volutpat augue purus, eu elementum diam auctor vitae. Sed semper condimentum molestie. Suspendisse euismod purus vitae ante vehicula sodales. Mauris auctor tincidunt tortor sit amet blandit. Nam pretium risus viverra, sagittis erat eu, lacinia magna. In congue tincidunt varius. Vestibulum tellus velit, porttitor eu sollicitudin ut, luctus ac metus. In mauris massa, consequat vel pretium id, tincidunt sit amet diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin sit amet orci elementum, semper mauris quis, sodales est. Nulla a leo ac elit volutpat iaculis. Nullam in tincidunt eros. Morbi elit orci, dapibus ac dapibus non, dapibus nec odio. Maecenas dapibus libero id laoreet congue.

Donec vel orci eu sapien mollis ultricies. Nunc venenatis dolor quis magna luctus viverra at eget dolor. Nunc consequat a ex at tempus. Curabitur ut dapibus nulla. Suspendisse ut lectus at justo efficitur laoreet at et arcu. Curabitur sit amet elit laoreet sapien aliquam eleifend. Quisque sit amet diam id nulla laoreet laoreet non nec nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum sed tempus lacus, sed lobortis augue. Nullam lectus dui, ornare ut egestas et, pharetra vitae neque.

Nulla et nunc ante. Nullam facilisis at tellus non lobortis. Vivamus scelerisque lacinia neque vitae vulputate. Nullam ut tortor rutrum, vulputate enim fringilla, laoreet ex. Sed volutpat, dui feugiat egestas fermentum, purus dui ultricies tellus, id pretium lacus sem vel sapien. Phasellus suscipit tortor massa, cursus facilisis nisl auctor eget. Nam id facilisis nibh. Donec consectetur odio sed lacinia dapibus. Maecenas leo justo, fermentum in dapibus et, pretium nec velit. Donec sagittis mollis ex, vitae euismod enim. Curabitur tincidunt est eget ipsum vestibulum, quis ultrices lacus hendrerit.

Etiam id lacus quis arcu lacinia tempus. Vestibulum pellentesque at ipsum eget convallis. Integer rhoncus lacus lacus, at placerat dolor porta eu. Aenean aliquam nulla id tristique bibendum. Quisque sit amet iaculis sem, et posuere magna. Morbi euismod non sem id viverra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed vestibulum ante risus, sed dapibus tellus rhoncus ac. Integer at quam non nulla mollis imperdiet.

Duis efficitur ullamcorper felis. Suspendisse sit amet nulla luctus, tincidunt mauris a, faucibus quam. Pellentesque non facilisis augue. Nam tempor nulla ac urna tempus interdum. Nam gravida lorem id convallis egestas. Suspendisse finibus egestas orci quis iaculis. Aliquam semper condimentum ipsum a tincidunt. Mauris vestibulum mauris nisi, commodo molestie nulla luctus vitae. Nulla volutpat mauris iaculis erat mattis, ut gravida eros lacinia. Cras efficitur est orci, id consequat lectus mattis luctus. Pellentesque tristique tincidunt pellentesque. Praesent lorem augue, pretium ut nibh in, faucibus tincidunt lectus. Sed semper, ligula vel egestas sollicitudin, orci est facilisis nunc, quis viverra turpis lectus a magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ullamcorper odio in sagittis condimentum. Aliquam leo dolor, pharetra vel consequat sed, sodales id arcu. Nullam maximus ac lectus vitae dapibus. In eget bibendum metus, sed sagittis metus. Fusce tincidunt tellus non nisl mattis hendrerit. Sed rhoncus malesuada nibh, id pellentesque tortor rutrum at. Praesent mollis tellus sollicitudin condimentum tincidunt. Quisque pretium mi luctus felis pulvinar imperdiet. Aliquam sit amet turpis eget magna congue dignissim. Praesent volutpat tempor venenatis. Quisque felis lectus, pharetra eget bibendum in, congue sit amet ex. Ut a sem et nibh hendrerit ornare quis at velit. Vestibulum quis ultricies ipsum. Integer orci libero, ultrices vel dui rhoncus, euismod aliquet purus.

Nunc semper iaculis erat, ac venenatis est. Nullam leo felis, malesuada vitae commodo vestibulum, malesuada at nisl. Cras cursus, dolor in feugiat tristique, lorem felis aliquet ex, ut molestie quam magna in felis. Etiam id augue dapibus, cursus id."

START_TIME=$(date +%s.%N)

# Loop through the specified number of times
for (( i=1; i<=TIMES; i++ ))
do
    # Generate the message by repeating 'a' i times
    MESSAGE="[ $i ] ${VIOLATOR_MESSAGE} "

    # Execute the client command with the incrementing message
    ./client $SERVER_PID "$MESSAGE"
done

# Record the end time
END_TIME=$(date +%s.%N)

# Calculate the duration in milliseconds
DURATION=$(echo "($END_TIME - $START_TIME)" | bc)

# Print the time taken
echo "Sent $TIMES Messages with 100 characters took $DURATION seconds to be received by the server."
